
source 'https://rubygems.org'
# group :production do
#   # Use Postgresql for ActiveRecord
#   gem 'pg'
# end

group :development, :test do
  # Use SQLite for ActiveRecord
  gem 'sqlite3'
end
# Use ActiveRecord as the ORM
gem 'sinatra-activerecord', '~> 2.0'

# Use rake to execute ActiveRecord's tasks
gem 'rake'

# Use JSON extension provided by the Sinatra::Contrib project
gem 'sinatra-contrib'
